name: AI Remediation Pipeline

on:
  workflow_run:
    workflows: ["Security Scan Pipeline"]
    types: [completed]
  workflow_dispatch:

jobs:
  remediate:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Download security results
      uses: actions/download-artifact@v4
      with:
        name: security-results
        path: security-results
        github-token: ${{ secrets.PAT_TOKEN }}
        
    - name: Generate AI fixes
      env:
        XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
      run: |
        python scripts/ai_remediation.py --input security-results/merged-results.json --output security-fixes/fixes.json
        
    - name: Upload fixes artifact
      uses: actions/upload-artifact@v4
      with:
        name: security-fixes
        path: security-fixes/
        
    - name: Apply fixes and create PR
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        python scripts/apply_fixes.py --fixes security-fixes/fixes.json
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git checkout -b fix/security-vulnerabilities-${{ github.run_id }}
        git add .
        git commit -m "Apply AI-generated security fixes"
        git push origin fix/security-vulnerabilities-${{ github.run_id }}
        gh pr create --title "Security Fixes for Run ${{ github.run_id }}" --body "Automated fixes for vulnerabilities" --base main --head fix/security-vulnerabilities-${{ github.run_id }}
