name: AI Security Remediation

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write
  security-events: write
  pull-requests: write

jobs:
  ai-fix-generation:
    runs-on: ubuntu-latest

    steps:

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Download security results
      uses: actions/download-artifact@v4
      with:
        name: security-results
        path: ./security-results/

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install AI dependencies
      run: |
        pip install openai requests python-dotenv

    - name: Generate AI fixes
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python scripts/ai_remediation.py \
          --input ./security-results/merged-results.json \
          --output ./fixes.json

    - name: Apply fixes
      run: |
        python scripts/apply_fixes.py --fixes ./fixes.json

    - name: Create fix branch
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "AI Security Bot"

        BRANCH_NAME="ai-security-fixes-$(date +%Y%m%d-%H%M%S)"
        git checkout -b $BRANCH_NAME

        git add .

        git commit -m "AI Security Fixes

Applied automated fixes for security vulnerabilities:
$(cat fixes-summary.txt)

Please review these changes carefully before merging.
" || exit 0

        git push origin $BRANCH_NAME

        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ env.BRANCH_NAME }}
        title: "AI Security Fixes - $(date +%Y-%m-%d)"
        body: |
          Automated Security Fixes
          This PR contains AI-generated fixes for security vulnerabilities found in the latest scan.
          
          $(cat fixes-summary.txt)
          
          - These fixes were generated by AI and need human review
          - Test thoroughly before merging
          - Some fixes might need manual adjustment
          - Check that functionality still works as expected
          
          - SAST Issues: $(jq '.sast | length' ./security-results/merged-results.json)
          - Dependency Issues: $(jq '.dependencies | length' ./security-results/merged-results.json)
          - DAST Issues: $(jq '.dast | length' ./security-results/merged-results.json)
          
          ---
          *Generated automatically by AI Security Bot*
        labels: |
          security
          automated-fix
          needs-review
        reviewers: |
          GwynethMorata
          malayu21
